//
//  DSHHarness.h
//  DSH
//
//  Supervises the `dsh-serve` process inside the Linux guest: chooses the
//  loopback port, launches the server, waits until it answers HTTP, restarts
//  it with back-off when it dies, and publishes state for the UI.
//

#import <Foundation/Foundation.h>
#import "DSHLogBuffer.h"
#import "DSHReadinessProbe.h"

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSInteger, DSHHarnessState) {
    DSHHarnessStateIdle = 0,   // never started
    DSHHarnessStateStarting,   // process launched, waiting for HTTP
    DSHHarnessStateReady,      // HTTP answered; UI may load
    DSHHarnessStateRestarting, // process exited, relaunch scheduled
    DSHHarnessStateFailed,     // gave up (too many crashes / launch error)
    DSHHarnessStateStopped,    // stopped on request
};

NSString *DSHHarnessStateName(DSHHarnessState state);

extern NSNotificationName const DSHHarnessStateDidChangeNotification;

/// Everything DSHHarness needs from the emulator, so tests can fake it.
@protocol DSHGuestProcessLauncher <NSObject>
/// Launches `executable` with `arguments` and `environment` as a child of
/// init. `line` receives every stdout/stderr line; `exit` fires once with the
/// exit code (negative on launch failure). Returns the guest pid, or a
/// negative error code if the process could not be created.
- (int)launchExecutable:(NSString *)executable
              arguments:(NSArray<NSString *> *)arguments
            environment:(NSDictionary<NSString *, NSString *> *)environment
                   line:(void (^)(NSString *line, BOOL isStdErr))line
                   exit:(void (^)(int exitCode))exit;
- (BOOL)killProcess:(int)pid signal:(int)signal;
@end

@interface DSHHarness : NSObject

+ (instancetype)shared;

- (instancetype)initWithLauncher:(id<DSHGuestProcessLauncher>)launcher NS_DESIGNATED_INITIALIZER;
- (instancetype)init NS_UNAVAILABLE;

@property (nonatomic, readonly) DSHHarnessState state;
@property (nonatomic, readonly) uint16_t port;
/// The bare origin, http://127.0.0.1:<port>/ once a port is chosen (may be nil
/// before start).
///
/// This is the *authority*, not the address the web view may load: under dsh
/// 0.2.x it answers 401 to anything without an auth cookie. Use
/// -authenticatedEntryURL to get somewhere the UI can actually go.
@property (nonatomic, readonly, nullable) NSURL *baseURL;
/// The URL the web view must load to enter the UI: the origin with the current
/// launch token attached, so the server answers 303 + Set-Cookie and the cookie
/// jar takes over from there. Nil until the server has announced its token.
@property (nonatomic, readonly, nullable) NSURL *authenticatedEntryURL;
/// The launch token of the current server process. Regenerated by every
/// restart, never logged, and nil until the server announces it.
@property (nonatomic, readonly, nullable) NSString *launchToken;
/// YES once a token has been captured for the current launch. The UI waits for
/// this rather than for `baseURL` alone, because a bare origin is a page that
/// cannot load.
@property (nonatomic, readonly) BOOL authenticationReady;
/// Bumped every time a new token is captured, i.e. on every (re)start. The web
/// view compares it against the generation it last authenticated with.
@property (nonatomic, readonly) NSUInteger authenticationGeneration;
@property (nonatomic, readonly) DSHLogBuffer *log;
@property (nonatomic, readonly) NSUInteger restartCount;
@property (nonatomic, readonly, nullable) NSString *lastError;
@property (nonatomic, readonly) int guestPid;
@property (nonatomic, readonly) NSTimeInterval lastStartupDuration;
/// Expected time from launch to first HTTP answer, from previous runs on this
/// device (25 s until measured once). Used for the startup progress estimate.
@property (nonatomic, readonly) NSTimeInterval expectedStartupDuration;
/// When the current launch started (nil when not starting).
@property (nonatomic, readonly, nullable) NSDate *launchStartedAt;

/// Guest command that serves the web UI. Default /usr/local/bin/dsh-serve.
@property (nonatomic, copy) NSString *serverExecutable;
/// Extra environment passed to the server (DSH_PORT is always set).
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> *extraEnvironment;
/// First port tried; default 3080. Up to 20 consecutive ports are probed.
@property (nonatomic) uint16_t preferredPort;
/// Seconds to wait for the first HTTP answer before declaring failure. Default 600.
/// This is the budget for the whole boot, not for one request; the dsh 0.2.x
/// guest takes roughly three minutes to compose its web plugin graph on an
/// emulated CPU, against ~30s under 0.1.x.
@property (nonatomic) NSTimeInterval startupTimeout;
/// Consecutive crashes tolerated before giving up. Default 4.
@property (nonatomic) NSUInteger maxConsecutiveCrashes;
/// Budget for one foreground health check. Default 15. Deliberately generous:
/// the check runs through an emulated CPU that may be cold or busy right after
/// a resume, and a late answer is not a dead server.
@property (nonatomic) NSTimeInterval healthCheckTimeout;
/// Failed health checks in a row before the server is restarted. Default 3.
/// A single timeout must never cost a 40-second guest reboot.
@property (nonatomic) NSUInteger healthCheckFailuresBeforeRestart;
/// Delay between health-check retries. Default 2.
@property (nonatomic) NSTimeInterval healthCheckRetryDelay;
/// Failures retained across app launches inside the ten-minute crash-loop
/// window. Test harness instances do not write this production state.
@property (nonatomic, readonly) NSUInteger recentPersistentFailureCount;
/// Diagnostic detail of the most recent health check (nil before the first).
@property (nonatomic, readonly, nullable) DSHProbeResult *lastHealthCheck;
/// Consecutive health-check failures observed so far.
@property (nonatomic, readonly) NSUInteger healthCheckFailures;

- (void)start;
- (void)stop;
- (void)restart;

/// Runs a health check; if the server stopped answering while the process is
/// still up (should not happen) it is restarted. Safe to call on foreground.
///
/// Tolerates transient failures: a single timeout — routine right after the
/// app resumes, or while the emulated CPU is loaded — is logged and retried,
/// and only `healthCheckFailuresBeforeRestart` consecutive failures restart the
/// server. A failure that proves the listener is gone (connection refused or a
/// 5xx) restarts immediately, so real crashes still recover on the first try.
- (void)verifyAliveWithCompletion:(nullable void (^)(BOOL alive))completion;

/// Like -verifyAliveWithCompletion:, but for a caller that has just rebuilt the
/// guest's listening sockets and therefore knows the answer this method is
/// about to produce is worthless: whatever the guest reported a moment ago was
/// measured against sockets that iOS had already destroyed.
///
/// It drops that cached answer — including "connection refused", which is the
/// *expected* result while the sockets are being recreated — so the check that
/// runs is a real one, and it bypasses the foreground debounce that would
/// otherwise re-assert the same stale answer without probing at all.
///
/// Use this exactly once per resume, from the scene lifecycle. A caller that
/// only wants an advisory check (say, the web view noticing a load error) should
/// keep using -verifyAliveWithCompletion: so it can still coalesce.
- (void)verifyAliveAfterResumeWithCompletion:(nullable void (^)(BOOL alive))completion;

/// Yes when the URL belongs to the current guest server, i.e. it shares an
/// authority with -baseURL. Ignores the query string, so the authenticated
/// entry URL and the bare origin both answer YES. The web view uses this to
/// decide whether a navigation should stay in-app.
- (BOOL)ownsURL:(nullable NSURL *)url;

/// Called by the web view when the server refused it with 401 (a stale or
/// absent cookie after a restart). Bumps the authentication generation so the
/// next load goes through the current entry URL, and logs the event with the
/// token redacted. Returns YES when a token is available to retry with.
///
/// The harness deliberately does not reload anything itself: the web view owns
/// its own navigation state, and a reload here would race the one the delegate
/// is already about to perform.
- (BOOL)noteAuthenticationFailureForURL:(nullable NSURL *)url;

/// Feeds a line of server output through the same path the guest's stdout
/// takes. Exposed so tests can drive token capture, and the redaction that
/// happens alongside it, without an emulator.
- (void)ingestServerLineForTesting:(NSString *)line;

@end

NS_ASSUME_NONNULL_END
